import type { Metadata } from 'next';
import './globals.css';
import AppHeader from '@/app_header/0_AppHeader/0_AppHeader';
import classes from './layout.module.css';

// МЕТОДАННЫЕ ------------------------------
export const metadata: Metadata = {
  title: 'Next.js & Tailwind Layout',
  description: 'Generated by create next app',
};

// HTML ROOT LAYOUT ------------------------
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // RENDERING HTML ROOT LAYOUT ------------
  return (
    <html lang="en" className={classes.html}>
      <body className={` ml-[20px]`}>
        <AppHeader />
        {children}
      </body>
    </html>
  );
}
